version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - ./backend/api/.env
    environment:
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost,http://localhost:5173
      - API_BASE_URL=http://localhost
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=dbkfz
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge